2018-09-28 11:11:23.667 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 11:11:23.667 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 11:11:56.121 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 11:11:56.121 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
