2018-09-28 10:08:28.339 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 10:08:38.353 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 10:08:48.363 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 10:08:58.372 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 10:09:08.377 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 10:09:09.917 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 10:09:18.381 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 10:09:28.388 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 10:09:38.393 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 10:09:48.396 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 10:09:58.407 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
